### ISSUE TITLE
Simplified middleware API

### ISSUE THREAD

**Issue by ronen** [SchemaPlus/schema_monkey#1]
@lowjoel attracting your attention since you're the only one other than me using schema_monkey just now.  (I should have tagged schema_monkey as 0.x.x.prex probably.) 

FYI in order to make client gems more DRY I'm considering changing the middleware API to replace this:

```ruby
module MyGem
  module Middleware
    module MyRandomModule
      def self.insert
         SchemaPlus::Middleware::<Group>::<Hook>.{pre|a}pend MyHook
      end
  
      class MyHook  < SchemaMonkey::Middleware::Base
        def call(env)
            ...etc...
        end
      end
   end
end
```

with

```ruby
module MyGem
  module Middleware
      module <Group> # e.g. Associations -- must match a SchemaMonkey::Middleware::Group module name
        module <Hook> # e.g. Reflection -- must match a SchemaMonkey::Middleware::Group::Hook module name

          # define any of these as needed...

          def before(env)
             # code to be called before the core implementation
          end

          def after(env)
            # code to be called after the core implementation
          end

          def around(env)  # essentially the same as the current "call(env)" method
            # do your stuff
            yield env                   # yields to the next on the stack. 
            # do your stuff
          end

          def implement(env)
             # completely replaces the core implementation.
          end
        end
    end
end
```

The execution sequence would be:

1. Call all the `before` methods.
2. Call all the `around` methods, bottoming out with the latest `implement` method
3. Call all the `after` methods.

Can also have hooks that are specific to a db adapter by including an extra module somewhere in the hierarchy:

```ruby
MyGem::Middleware::Postgresql::Group::Hook
MyGem::Middleware::Group::Postgresql::Hook
MyGem::Middleware::Group::Hook::Postgresql
```

What do you think?

**Comment by lowjoel** [comment]
Much less verbose, and much cleaner. There might be some considerations regarding eager loading, but apart from that it sounds good.

**Comment by ronen** [comment]
Great, glad you like it.  I'll head in this direction.   Will do a major version bump when it's ready.

Also, I realized recently that a client gem should be able to define a new middleware hook for new capabilities.  E.g. `schema_plus_views` adds `create_view(name, sql, options)` so you can define views in a migration.  But it should ideally also provide a hook `Middleware::Migration::View` so that other gems or applications can modify it as needed.

Sigh, just as I was thinking SchemaMonkey was stable and I could move on...

**Comment by ronen** [comment]
Done and release v1.0.1

It also lets you define your own new middleware stacks, which other client gems can use:
 
```ruby
module MyGem
  module Middleware
    module WhereverYouWant
      module NewStack
        ENV = [:field, :other_field]
      end
    end
  end
end
```

With that it now eats its own dogfood:  The insertions into ActiveRecord that define the extension API are just a module `SchemaMonkey::CoreExtensions` which is loaded using `SchemaMonkey.register` just like any other gem.
