### ISSUE TITLE
its-it break rspec 3.2.1

### ISSUE THREAD

**Issue by rupurt** [SchemaPlus/schema_monkey#2]
https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/example_group.rb#L40

RSpec should probably do a better job of detecting the method but I also think one should not add methods to Kernel. If using `&it` is required to simplify a large amount of chaining, it may be a smell that you haven't refactored enough, and hiding such a smell may not be the best idea.

cc/ @ryanong

**Comment by ronen** [comment]
@rupurt Thanks for the report -- but I can't reproduce any breakage.  I've tried rspec-core 3.2.1, 3.2.2, and master (3.3.0.pre), using MRI 2.1.5p273, and the specs all pass without any errors.  Can you give details on how to get it to break?

>  If using &it is required to simplify a large amount of chaining, it may be a smell that you haven't refactored enough, and hiding such a smell may not be the best idea.

I disagree about the smell of refactoring .  I consider it essentially a more compact and readable shorthand for loop comprehensions.  Just like `map &:to_s` is more readable shorthand for `map {|x| x.to_s}`, IMHO `map &it["foo"]` is more readable than `map { |x| x["foo"] }`.

That said, I do agree that adding methods to Kernel is dicey, and if it does cause trouble of course it'd have to go.  But I've been using its-it for years and have yet to encounter a case of it causing any trouble.

**Comment by ryanong** [comment]
You could always use a constant instead of a method. `map &It["foo"]` or `map &IT["foo"]`

**Comment by rupurt** [comment]
rspec 3.2.3 has the patch which fixes the conflict so closing issue.
