### ISSUE TITLE
Rake tasks disappeared in v2.1; using schema_monkey with Padrino?

### ISSUE THREAD

**Issue by fj** [SchemaPlus/schema_monkey#5]
We were previously using schema_monkey to insert some Rake tasks for us:

```ruby
# Rakefile
# [...]
require 'schema_monkey/rake'
SchemaMonkey::Rake.insert('ar:schema:dump', 'ar:schema:load')
```

so that we get the appropriate SchemaPlus-aware behavior in these Rake tasks.

Unfortunately, it doesn't seem like there's a way to do this anymore.

What is the correct replacement for this in a Padrino environment? Is the idea that we don't actually need this at all, and that we'd just use `require 'schema_plus/indexes'` instead?

**Comment by ronen** [comment]
> Is the idea that we don't actually need this at all, and that we'd just use require 'schema_plus/indexes' instead?

Yep, that's the Idea, should be all you need.

**Comment by fj** [comment]
Good deal. Closing this.
